version: "3.9"
services:
  interface_service:
    restart: always
    build:
      context: ../inscription_ms
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    container_name: servicio_interface
    extra_hosts:
      - "host.docker.internal:host-gateway"